name: django

on:
  push:
    branches: [ master ]

jobs:
  deploy_zip:
    name: deploy django lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install poetry
        uses: dschep/install-poetry-action@v1.3
      - name: zip package
        run: ./build-lambda.sh
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ListenalongDjango
          zip_file: package.zip
