name: django

on:
  push:
    branches: [ master ]

jobs:
  deploy_zip:
    name: deploy django lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - uses: dschep/install-poetry-action@v1.3
      - run: poetry export -r requirements.txt -o requirements.txt
      - name: Deploy code to Lambda
        uses: mariamrf/py-lambda-action@v1.0.0
        with:
          lambda_layer_arn: ${{ secrets.AWS_LAMBDA_LAYER_ARN }}
          lambda_function_name: 'ListenalongDjango'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
